### ISSUE TITLE
Inaccurate token mappings between Antlr4 tokens and plagiarismdetection tokens.

### ISSUE THREAD

**Issue by Dexte-R** [WING-NUS/SSID#36]
Inaccurate token mappings may be causing similarity percentages to be less accurate because some redundant tokens are being treated as a similarity whereas some important tokens are not being accounted for.

**Comment by Riyas97** [comment]
Upon further debug and observation of antlr tokens in python, some issues were found:

1. Some tokens in [python3_tokens](https://github.com/WING-NUS/SSID/blob/master/lib/antlr/grammars/bin/python3/python3_tokens) do not have a mapping in [python3_token_mappings](https://github.com/WING-NUS/SSID/blob/master/lib/antlr/grammars/bin/python3/python3_token_mappings). This include tokens such as `LT_EQ`, `GT_EQ` and etc. Because of this, an exception occurs at [ANTLRDynamicTokenizer.java](https://github.com/WING-NUS/SSID/blob/master/lib/java/PlagiarismDetection/src/Tokenizer/ANTLRDynamicTokenizer.java#L235) as the program is unable to get the key-value pair for these tokens.

2. If you look at the tokens in [python3_tokens](https://github.com/WING-NUS/SSID/blob/master/lib/antlr/grammars/bin/python3/python3_tokens), some tokens though they have different names, they have the same number which makes them replicated twice. In the latter stages of the program when these tokens and their corresponding numbers are extracted and put in a [hash table](https://github.com/WING-NUS/SSID/blob/master/lib/java/PlagiarismDetection/src/Tokenizer/ANTLRDynamicTokenizer.java#L145), tokens with duplicate numbers are replaced anyways. Hence, I think we can remove these tokens with duplicate numbers and as much as I have tested so far, they don't affect the logic of the program. Also, for these duplicated tokens, some have a mapping in [python3_token_mappings](https://github.com/WING-NUS/SSID/blob/master/lib/antlr/grammars/bin/python3/python3_token_mappings) while others don't. For example, tokens `LT_EQ` and `GT_EQ` had the same numbers (78. 77 respectively) as tokens `'>='` and `'<='`. But,  tokens `'>='` and `'<='` had  a mapping in [python3_token_mappings](https://github.com/WING-NUS/SSID/blob/master/lib/antlr/grammars/bin/python3/python3_token_mappings) while tokens `LT_EQ` and `GT_EQ` did not. 

3. Another interesting problem that was also found out from the above example in point 2 was that since `LT_EQ` and `GT_EQ` had the same numbers (78. 77 respectively) as tokens `'>='` and `'<='`, when these tokens were extracted into a  [hash table](https://github.com/WING-NUS/SSID/blob/master/lib/java/PlagiarismDetection/src/Tokenizer/ANTLRDynamicTokenizer.java#L145), by right, tokens `LT_EQ` and `GT_EQ` should have been replaced by  tokens `'>='` and `'<='` and the issue mentioned in point 1 would not have happened for tokens `LT_EQ` and `GT_EQ`. But that did not happened due to another bug in the code. The method of parsing the tokens is attached below:

![Screenshot from 2020-09-05 19-43-07](https://user-images.githubusercontent.com/42403047/92304392-1becae80-efb0-11ea-932b-ea7641701035.png)

As you can see, the tokens are split by '=' and in the case for tokens `'>='` and `'<='`, it does not results in proper parsing of the tokens and their numbers as these tokens have a '=' in them. If we were to remove these symbols and just use tokens `LT_EQ` and `GT_EQ`, then I guess the above piece of code can be kept.

**Comment by knmnyn** [comment]
Sounds like a parse for `>=` and `<=` need to be done earlier in the parser before a check for `=` as a token separator.  
If you use `LT_EQ` and `GT_EQ` and it solves the problem, then it is fine.
